# common:
debug: True
output_path: "./data/02_output/"

# stare:
stare_name: "STARE"

stare_path: "./data/01_input/STARE/"
stare_images_url: "https://cecas.clemson.edu/~ahoover/stare/probing/stare-images.tar"
stare_labels_url: "https://cecas.clemson.edu/~ahoover/stare/probing/labels-ah.tar"

# drive:
drive_name: "DRIVE"

drive_path: "./data/01_input/DRIVE/"

# chasedb1:
chasedb1_name: "CHASEDB1"

chasedb1_path: "./data/01_input/CHASEDB1/"
chasedb1_url: https://researchdata.kingston.ac.uk/96/1/CHASEDB1.zip
