# data
datapath: "./data/01_raw/"

# stare:
stare_path: "./data/01_raw/STARE/"
stare_images_url: "https://cecas.clemson.edu/~ahoover/stare/probing/stare-images.tar"
stare_labels_url: "https://cecas.clemson.edu/~ahoover/stare/probing/labels-ah.tar"

# drive:
drive_path: "DRIVE/"

# vessel_segmentation pipeline:
input_path: "./data/01_raw/DRIVE/"
output_path: "./data/02_intermediate/"
image_plot_title: "Image and Mask"
image_plot_filename: "image_and_mask.png"
result_plot_title: "Ground truth and predicted mask"
result_plot_filename: "results.png"
debug: True
