# data
datapath: "./data/01_raw/"

# stare:
stare_path: "STARE/"
stare_images_url: "https://cecas.clemson.edu/~ahoover/stare/probing/stare-images.tar"
stare_labels_url: "https://cecas.clemson.edu/~ahoover/stare/probing/labels-ah.tar"

# drive:
drive_path: "DRIVE/"

# chasedb1:
chasedb1_path: "CHASEDB1/"
chasedb1_url: https://researchdata.kingston.ac.uk/96/1/CHASEDB1.zip

# vessel_segmentation pipeline:
input_path: "./data/01_raw/DRIVE/"
output_path: "./data/02_intermediate/"
image_plot_title: "Image and Mask"
image_plot_filename: "image_and_mask.png"
result_plot_title: "Ground truth and predicted mask"
result_plot_filename: "results.png"
debug: True
