from kedro.pipeline import Pipeline, node

from .feature_extraction import create_dataset
from .models_and_predictions import predict_model, train_adaboost, train_knn, train_logitboost, undersampling
from .visualisation import plot_images, plot_results

from .prepare import prepare_stare, prepare_drive, prepare_chasedb1


def create_pipeline(**kwargs):
    stare_pipeline = Pipeline(
        [
            node(
                func=prepare_stare,
                inputs=["params:stare_path",
                        "params:stare_images_url",
                        "params:stare_labels_url",
                        "params:debug"],
                outputs=["STARE_train_photos",
                         "STARE_train_masks",
                         "STARE_test_photos",
                         "STARE_test_masks"],
                name="STARE"
            ),
            node(
                func=plot_images,
                inputs=["STARE_train_photos",
                        "STARE_train_masks",
                        "params:stare_name",
                        "params:output_path"],
                outputs=None,
                name="plot_STARE",
            ),
            node(
                func=create_dataset,
                inputs=["STARE_train_photos",
                        "STARE_train_masks"],
                outputs=["STARE_train_features",
                         "STARE_train_labels"],
                name="STARE_dataset",
            ),
            node(
                func=undersampling,
                inputs=["STARE_train_features",
                        "STARE_train_labels"],
                outputs=["STARE_train_features_under",
                         "STARE_train_labels_under"],
                name="STARE_undersampling",
            ),
            node(
                func=train_knn,
                inputs=["STARE_train_features_under",
                        "STARE_train_labels_under"],
                outputs="STARE_knn_classifier",
                name="STARE_train",
            ),
            node(
                func=predict_model,
                inputs=["STARE_knn_classifier",
                        "STARE_test_photos",
                        "STARE_test_masks"],
                outputs="STARE_pred_images",
                name="STARE_predict_model",
            ),
            node(
                func=plot_results,
                inputs=["STARE_test_photos",
                        "STARE_test_masks",
                        "STARE_pred_images",
                        "params:stare_name",
                        "params:output_path"],
                outputs=None,
                name="STARE_plot_results",
            ),
        ]
    )

    drive_pipeline = Pipeline(
        [
            node(
                func=prepare_drive,
                inputs=["params:drive_path",
                        "params:debug"],
                outputs=["DRIVE_train_photos",
                         "DRIVE_train_masks",
                         "DRIVE_test_photos",
                         "DRIVE_test_masks"],
                name="DRIVE"
            ),
            node(
                func=plot_images,
                inputs=["DRIVE_train_photos",
                        "DRIVE_train_masks",
                        "params:drive_name",
                        "params:output_path"],
                outputs=None,
                name="plot_DRIVE",
            ),
            node(
                func=create_dataset,
                inputs=["DRIVE_train_photos",
                        "DRIVE_train_masks"],
                outputs=["DRIVE_train_features",
                         "DRIVE_train_labels"],
                name="DRIVE_dataset",
            ),
            node(
                func=undersampling,
                inputs=["DRIVE_train_features",
                        "DRIVE_train_labels"],
                outputs=["DRIVE_train_features_under",
                         "DRIVE_train_labels_under"],
                name="DRIVE_undersampling",
            ),
            node(
                func=train_knn,
                inputs=["DRIVE_train_features_under",
                        "DRIVE_train_labels_under"],
                outputs="DRIVE_knn_classifier",
                name="DRIVE_train",
            ),
            node(
                func=predict_model,
                inputs=["DRIVE_knn_classifier",
                        "DRIVE_test_photos",
                        "DRIVE_test_masks"],
                outputs="DRIVE_pred_images",
                name="DRIVE_predict_model",
            ),
            node(
                func=plot_results,
                inputs=["DRIVE_test_photos",
                        "DRIVE_test_masks",
                        "DRIVE_pred_images",
                        "params:drive_name",
                        "params:output_path"],
                outputs=None,
                name="DRIVE_plot_results",
            ),
        ]
    )

    chasedb1_pipeline = Pipeline(
        [
            node(
                func=prepare_chasedb1,
                inputs=["params:chasedb1_path",
                        "params:chasedb1_url",
                        "params:debug"],
                outputs=["CHASEDB1_train_photos",
                         "CHASEDB1_train_masks",
                         "CHASEDB1_test_photos",
                         "CHASEDB1_test_masks"],
                name="CHASEDB1"
            ),
            node(
                func=plot_images,
                inputs=["CHASEDB1_train_photos",
                        "CHASEDB1_train_masks",
                        "params:chasedb1_name",
                        "params:output_path"],
                outputs=None,
                name="plot_CHASEDB1",
            ),
            node(
                func=create_dataset,
                inputs=["CHASEDB1_train_photos",
                        "CHASEDB1_train_masks"],
                outputs=["CHASEDB1_train_features",
                         "CHASEDB1_train_labels"],
                name="CHASEDB1_dataset",
            ),
            node(
                func=undersampling,
                inputs=["CHASEDB1_train_features",
                        "CHASEDB1_train_labels"],
                outputs=["CHASEDB1_train_features_under",
                         "CHASEDB1_train_labels_under"],
                name="CHASEDB1_undersampling",
            ),
            node(
                func=train_knn,
                inputs=["CHASEDB1_train_features_under",
                        "CHASEDB1_train_labels_under"],
                outputs="CHASEDB1_knn_classifier",
                name="CHASEDB1_train",
            ),
            node(
                func=predict_model,
                inputs=["CHASEDB1_knn_classifier",
                        "CHASEDB1_test_photos",
                        "CHASEDB1_test_masks"],
                outputs="CHASEDB1_pred_images",
                name="CHASEDB1_predict_model",
            ),
            node(
                func=plot_results,
                inputs=["CHASEDB1_test_photos",
                        "CHASEDB1_test_masks",
                        "CHASEDB1_pred_images",
                        "params:chasedb1_name",
                        "params:output_path"],
                outputs=None,
                name="CHASEDB1_plot_results",
            ),
        ]
    )

    return stare_pipeline + drive_pipeline + chasedb1_pipeline
